title: TechWorkshop L300 Understanding XDR
description: In this course, you will learn ...
theme: just-the-docs

aux_links:
  "Understanding XRD":
    - "https://github.com/microsoft/TWL300-Understanding-XDR"

callouts_level: quiet # or loud
callouts:
  highlight:
    color: yellow
  important:
    title: Important
    color: blue
  new:
    title: New
    color: green
  note:
    title: Note 
    color: purple
  warning:
    title: Warning
    color: red
